name: GreenIT Analysis

on:
  push:
    branches:
      - main

jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Installer Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      # 3) Installer dépendances du frontend
      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      # 4) Générer automatiquement sample_data.json
      - name: Generate sample data
        run: |
          npm install -g dummy-json
          dummy-json sample_data.hbs > frontend/public/sample_data.json

      # 5) Builder l'application
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # 6) Démarrer nginx via Docker
      - name: Start nginx
        run: |
          docker compose up --detach

      # 7) Attendre que le site réponde
      - name: Wait for server
        uses: benel/wait-for-response@v1
        with:
          url: "http://localhost/"
          expected-status: 200
          timeout: 30000

      # 8) Installer GreenIT CLI
      - name: Install GreenIT-Analysis
        run: |
          git clone https://github.com/cnumr/GreenIT-Analysis-cli.git
          cd GreenIT-Analysis-cli
          npm install

      # 9) Lancer l’analyse GreenIT
      - name: Run GreenIT scenario
        run: |
          cd GreenIT-Analysis-cli
          ./bin/greenit analyse ../scenarios/buy_train_ticket.yml ../greenit_report.html --format html --headless true

      # 10) Publier le rapport en artefact
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: greenit-report
          path: greenit_report.html
