name: GreenIT Analysis

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prepare-app:
    uses: ./.github/workflows/app-start.yml

  analyse:
    needs: prepare-app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GreenIT CLI
        run: |
          git clone https://github.com/cnumr/GreenIT-Analysis-cli.git greenit-cli
          cd greenit-cli
          npm install
          npm link

      - name: Run GreenIT analysis
        run: |
          greenit analyse ./scenarios/buy_train_ticket.yml ./greenit_report.html --format html --headless true --ci

      - name: Upload GreenIT report
        uses: actions/upload-artifact@v4
        with:
          name: greenit-report
          path: greenit_report.html
